### ISSUE TITLE
[Bug?] Unable to add Yeta Wrench

### ISSUE THREAD

**Issue by GenghisKahn** [Vazkii/Morph-o-Tool#12]
I am unable to add the "Yeta Wrench" from Ender IO, the "Wrench" from ExtraUtils2, or the "PA Wrench" from Progressive Automation.

I am using the default configs.

Minecraft Version - 1.9.4
Forge Version - 12.17.0.1937
Mod Version - 1.0-2

**Comment by ConnorRowe** [comment]
It's not a bug, you need to add the items to the config file in the 'whitelisted items' field. You you need to add:
`enderio:itemYetaWrench`
`extrautils2:Wrench`
`progressiveautomation:wrench`

**Comment by jmcaffee** [comment]
From the description on the curse project page, I'd have thought the `Whitelisted Names` list would pull in the Yeta Wrench because `wrench` is listed there.

Is the list case sensitive?
