### ISSUE TITLE
Morph-o-Tool issue with Wand of the Forest.

### ISSUE THREAD

**Issue by GirafiStudios** [Vazkii/Morph-o-Tool#13]
When adding Wand of the Forest to the Morph-o-Tool and hovering over a block from Botania it gives a internal server error and gives the following error in the console: https://gist.github.com/GirafiStudios/dc902a5718d9026960f38684f486bfe5
It also makes the Wand of Forest dissapear from the Morph-o-Tool completly.

**Comment by b0bst3r** [comment]
Also occurs with Actually Additions Laser Wrench, EnderIO Yeta Wrench, in fact the only wrench I've managed to not crash is the Rftools wrench.

These crashes are all in SMP BTW.
http://i.imgur.com/237OZ0Y.png

**Comment by Carrots4U** [comment]
Can confirm, happens on the All the Mods testing server also.

**Comment by Vazkii** [comment]
Fixed with https://github.com/Vazkii/Morph-o-Tool/commit/564a83bb014fd2b9661789a9d141bff6fb8f9cb8
