### ISSUE TITLE
1.10.2-Morph-o-tool Permanently Becomes a Laser Wrench from Actually Additions.

### ISSUE THREAD

**Issue by WenXin20** [Vazkii/Morph-o-Tool#18]
If you combine the Morph-O-Tool with the laser wrench from the Actually Additions Mod and then look at a block from that mod, the tool permanently becomes the laser wrench.

**Comment by Vazkii** [comment]
I'd take it up with Actually Additions. It looks like it's setting its stack rather than modifying it.

**Comment by Ellpeck** [comment]
Yes, you can close this, it is indeed my fault.
As this is pretty old code, I am just setting the stack's NBT Tag to a completely new one when clearing the positional data that is stored instead of just deleting the actual coordinates from the NBT Tag.
