### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by C0rn3j** [Vazkii/Morph-o-Tool#21]
Forge 2075, mod version 1.0.8
http://pastebin.com/qrhpBtAU

**Comment by Vazkii** [comment]
You need to install AutoRegLib for the newest versions.

**Comment by c0rn3j** [comment]
>    UC  AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar)

From the log I posted.

**Comment by Vazkii** [comment]
Weird, because that log says it can't find it. Let me have a look.

**Comment by Vazkii** [comment]
Just tried loading it ingame and it works fine. Not sure why it's breaking for you.

**Comment by Vazkii** [comment]
Nevermind, I got it to break.

**Comment by Vazkii** [comment]
Try this: http://puu.sh/qUxDJ/9eaa9ca371.jar

**Comment by C0rn3j** [comment]
Crashy crashy: http://pastebin.com/yADU2kcs

**Comment by Vazkii** [comment]
fuck I know why

**Comment by Vazkii** [comment]
Try this one http://puu.sh/qUydq/eb4a4b8c08.jar

**Comment by C0rn3j** [comment]
That one works!

**Comment by Vazkii** [comment]
yay!
