### ISSUE TITLE
Unable to add Immersive Engineering Hammer

### ISSUE THREAD

**Issue by LuigiHutch** [Vazkii/Morph-o-Tool#23]
Minecraft Version - 1.10.2
Forge Version - 12.18.1.2066
Morph-o-Tool Version - 1.0-11
Immersive Engineering Version: 0.10-38

I am unable to add the immersive engineering hammer to the tool even though the mod states that hammers should be whitlisted.

I also tried adding immersiveengineering:tool to the whitelist but it still wont be added to the tool

**Comment by Vazkii** [comment]
With the latest version you can add that with the right metadata using immersiveengineering:tool:(meta)
