### ISSUE TITLE
Morph-O-Tool doesn't recognize SCM Circuit

### ISSUE THREAD

**Issue by ElvenChaos** [Vazkii/Morph-o-Tool#27]
_**I highly suspect the issue and cause are the same as from issue https://github.com/Vazkii/Morph-o-Tool/issues/15 due to the involvement of MCMultipart**_

The Morph-O-Tool, with the Super Circuit Maker screwdriver, doesn't recognize the Redstone Circuit or any pieces contained within it. The Tool recognizes the one normal block/tile, which is the "Block Update Detector."

**Comment by Vazkii** [comment]
Indeed this is a dupe of #15.
