### ISSUE TITLE
[Suggestion] 'Default tool'

### ISSUE THREAD

**Issue by SynfulChaot** [Vazkii/Morph-o-Tool#3]
Would it be possible for a config that allows it to default to any tool in particular, say if we wanted it to appear, by default, as a wrench when rotating vanilla blocks?

**Comment by Vazkii** [comment]
The morphing tool itself does rotating.

**Comment by SynfulChaot** [comment]
I know it does rotating.  I was thinking aesthetics.

**Comment by Vazkii** [comment]
Meh >_>
