### ISSUE TITLE
Server Multiplayer other players hands disapear when tool changes

### ISSUE THREAD

**Issue by MoreThanHidden** [Vazkii/Morph-o-Tool#30]
**Example Gif:**
![morph-o-tool multiplayer](https://cloud.githubusercontent.com/assets/1351964/20238668/ac867108-a92b-11e6-9b6e-486c21509b2f.gif)

**Minecraft Version:** 1.10.2
**Mod Version:** Morph-o-Tool-1.0-12.jar

**Issue:**
Server Multiplayer other players hands disapear when tool changes.

**Comment by Segaja** [comment]
I would love to see this bug fixed some day. It is the one thing that stops me from using the tool.
