### ISSUE TITLE
[Suggestion] Add a way to get a tool back

### ISSUE THREAD

**Issue by PapiDimmi** [Vazkii/Morph-o-Tool#40]
Let’s say I add a wrench to the morphing tool that isn’t compatible with Morph-o-Tool, so it ends up not working, and I wasted my wrench. I would love to get that wrench back.

It would be nice if you could put the Morph-o-Tool in a crafting grid and remove the last wrench that was added to the morphing tool from it, similar to how you remove upgrades from backpacks in the Iron Backpacks mod.

I don’t know if there’s already a way to get wrenches back that I don’t know about, but there doesn’t seem like there is.

**Comment by Vazkii** [comment]
Drop the morphing tool while sneaking.

**Comment by PapiDimmi** [comment]
Thanks.
