### ISSUE TITLE
[1.15.2] Server crash

### ISSUE THREAD

**Issue by Quu1337** [Vazkii/Morph-o-Tool#54]
Heyo.

No idea if its actually from morph-o-tool or refined storage, but crash log seems to be blaming morph mainly for it.

https://pastebin.com/fDquYYPe

Also lots of random errors in console

https://pastebin.com/pRXZhgDh
(sorry for the spacing, copying from console works like shit)

**Comment by Vazkii** [comment]
The crash appears to be in industrial foregoing using a client method
