### ISSUE TITLE
Morph-o-Tool don't respect items changing its name.

### ISSUE THREAD

**Issue by Wojbie** [Vazkii/Morph-o-Tool#9]
Tested using psi spell drive. When spell drive changes its name (due to me changing spell inside) the morph-o-toll still shows old name it had when it was fist bound into morp-o-tool instead of new one with new spell name in brackets.

EDIT: After unbinding the bound tool (drive) from the morph it still shows old name instead of new while keeping new spell inside.

**Comment by Vazkii** [comment]
It needs to keep some name in reference. Detecting name changes is possible but it's way too minor to worry about it.
